### ISSUE TITLE
paralyzed --> replace with lastMove()

### ISSUE THREAD

**Issue by WilliCodes** [WilliCodes/FatSquirrel#5]

**Comment by Genwar** [comment]
Arbeite gerade daran

**Comment by Genwar** [comment]
Hab alles was mit paralyzed zu tun hatte mit lastMove<3 für paralyzed ersetzt. Allerdings gibt es beim testen in der Laufzeit beim Debug der Character "cant Move" aus, obwohl sie sich bewegen.
